### ISSUE TITLE
Errors when using as dependency

### ISSUE THREAD

**Issue by FreakTheMighty** [schwa/SwiftGLTF#1]
I'm getting a few errors when I try to use your library as a dependency to my own Swift library. When I open the xcode project from this repo directly everything looks fine. One difference I notice is that our dependencies resolve differently, but these errors don't appear to be related to this library's dependencies. Any thoughts or hints would be much appreciated.

![image](https://user-images.githubusercontent.com/247092/211107880-57f92592-5859-4855-bb0d-ba68240ff6c6.png)

**Comment by schwa** [comment]
Ah it looks like it's not using the version of the "Everything" dependency specified in Package.resolved and the newer version of Everything breaks it. I'll fix the issue or I'll version it correctly.

**Comment by schwa** [comment]
The failing file wasn't even being used. Easy fix.

**Comment by FreakTheMighty** [comment]
Thank you! I’ll give it a try.
